import { IDetailMatchInfo } from '@/types/info'

export const DETAIL_MATCH_INFO: IDetailMatchInfo[] = [
  {
    id: 1,
    date: '2025-07-11',
    time: '20:00',
    stage: '4강 1경기',
    teamA: '-',
    teamB: '-',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: false,
  },
  {
    id: 2,
    date: '2025-07-11',
    time: '20:00',
    stage: '4강 2경기',
    teamA: '-',
    teamB: '-',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: false,
  },
  {
    id: 3,
    date: '2025-07-12',
    time: '20:00',
    stage: '3/4위전',
    teamA: '-',
    teamB: '-',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: false,
  },
  {
    id: 4,
    date: '2025-07-12',
    time: '20:00',
    stage: '결승전',
    teamA: '-',
    teamB: '-',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: false,
  },
  {
    id: 11,
    date: '2025-07-07',
    time: '21:00',
    stage: '스크림',
    teamA: '팀 A',
    teamB: '팀 B',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: true,
    sets: [
      {
        setNumber: 1,
        map: 'asdf',
        roundsWin: [
          'teamB',
          'teamA',
          'teamA',
          'teamA',
          'teamB',
          'teamA',
          'teamB',
          'teamB',
          'teamA',
          'teamB',
          'teamA',
          'teamB',
          'teamB',
          'teamB',
        ],
        teamA: {
          name: '팀 A',
          score: 6,
          players: [
            {
              name: '실프',
              kills: 12,
              deaths: 8,
              assists: 3,
              rating: 1.35,
              operators: [
                'ash',
                'jager',
                'ash',
                'jager',
                'twitch',
                'wamai',
                'ash',
                'jager',
                'ash',
                'jager',
                'twitch',
                'wamai',
                'jager',
                'twitch',
                'wamai',
              ],
            },
            {
              name: '이로나묭 치카',
              kills: 12,
              deaths: 8,
              assists: 3,
              rating: 1.35,
              operators: ['ash', 'jager', 'ash', 'jager', 'twitch', 'wamai'],
            },
          ],
        },
        teamB: {
          name: '팀 B',
          score: 8,
          players: [
            {
              name: '빅헤드',
              kills: 12,
              deaths: 8,
              assists: 3,
              rating: 1.35,
              operators: ['ash', 'jager', 'ash', 'jager', 'twitch', 'wamai'],
            },
            {
              name: '금사향',
              kills: 12,
              deaths: 8,
              assists: 3,
              rating: 1.35,
              operators: ['ash', 'jager', 'ash', 'jager', 'twitch', 'wamai'],
            },
          ],
        },
      },
      {
        setNumber: 2,
        map: 'asdf',
        roundsWin: ['teamB', 'teamA', 'teamA', 'teamA', 'teamB'],
        teamA: {
          name: '팀 A',
          score: 6,
          players: [
            {
              name: '김스트림',
              kills: 12,
              deaths: 8,
              assists: 3,
              rating: 1.35,
              operators: ['ash', 'jager', 'ash', 'jager', 'twitch', 'wamai'],
            },
            {
              name: '김스트림',
              kills: 12,
              deaths: 8,
              assists: 3,
              rating: 1.35,
              operators: ['ash', 'jager', 'ash', 'jager', 'twitch', 'wamai'],
            },
          ],
        },
        teamB: {
          name: '팀 B',
          score: 8,
          players: [
            {
              name: '김스트림',
              kills: 12,
              deaths: 8,
              assists: 3,
              rating: 1.35,
              operators: ['ash', 'jager', 'ash', 'jager', 'twitch', 'wamai'],
            },
            {
              name: '김스트림',
              kills: 12,
              deaths: 8,
              assists: 3,
              rating: 1.35,
              operators: ['ash', 'jager', 'ash', 'jager', 'twitch', 'wamai'],
            },
          ],
        },
      },
    ],
  },
  {
    id: 12,
    date: '2025-07-07',
    time: '21:00',
    stage: '스크림',
    teamA: '팀 C',
    teamB: '팀 D',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: true,
  },
  {
    id: 13,
    date: '2025-07-07',
    time: '22:30',
    stage: '스크림',
    teamA: '팀 A',
    teamB: '팀 C',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: true,
  },
  {
    id: 14,
    date: '2025-07-07',
    time: '22:30',
    stage: '스크림',
    teamA: '팀 B',
    teamB: '팀 D',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: true,
  },
] as const
