export const DETAIL_MATCH_INFO = [
  {
    id: 1,
    date: '2025-07-11',
    time: '20:00',
    stage: '4강 1경기',
    teamA: '-',
    teamB: '-',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: false,
  },
  {
    id: 2,
    date: '2025-07-11',
    time: '20:00',
    stage: '4강 2경기',
    teamA: '-',
    teamB: '-',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: false,
  },
  {
    id: 3,
    date: '2025-07-12',
    time: '20:00',
    stage: '3/4위전',
    teamA: '-',
    teamB: '-',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: false,
  },
  {
    id: 4,
    date: '2025-07-12',
    time: '20:00',
    stage: '결승전',
    teamA: '-',
    teamB: '-',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: false,
  },
  {
    id: 11,
    date: '2025-07-07',
    time: '21:00',
    stage: '스크림',
    teamA: '팀 A',
    teamB: '팀 B',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: true,
  },
  {
    id: 12,
    date: '2025-07-07',
    time: '21:00',
    stage: '스크림',
    teamA: '팀 C',
    teamB: '팀 D',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: true,
  },
  {
    id: 13,
    date: '2025-07-07',
    time: '22:30',
    stage: '스크림',
    teamA: '팀 A',
    teamB: '팀 C',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: true,
  },
  {
    id: 14,
    date: '2025-07-07',
    time: '22:30',
    stage: '스크림',
    teamA: '팀 B',
    teamB: '팀 D',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: true,
  },
] as const
