import { IDetailMatchInfo } from '@/types/info'

export const DETAIL_MATCH_INFO: IDetailMatchInfo[] = [
  {
    id: 1,
    date: '2025-07-11',
    time: '20:00',
    stage: '4강 1경기',
    teamA: '빅헤드',
    teamB: '핑맨',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: false,
  },
  {
    id: 2,
    date: '2025-07-11',
    time: '20:00',
    stage: '4강 2경기',
    teamA: '실프',
    teamB: '뱅',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: false,
  },
  {
    id: 3,
    date: '2025-07-12',
    time: '20:00',
    stage: '3/4위전',
    teamA: '-',
    teamB: '-',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: false,
  },
  {
    id: 4,
    date: '2025-07-12',
    time: '20:00',
    stage: '결승전',
    teamA: '-',
    teamB: '-',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: false,
  },
  {
    id: 11,
    date: '2025-07-07',
    time: '21:00',
    stage: '스크림',
    teamA: '빅헤드',
    teamB: '핑맨',
    scoreA: 1,
    scoreB: 0,
    status: 'live',
    maps: ['해안선', '오리건', '빌라'],
    isScrim: true,
    sets: [],
  },
  {
    id: 12,
    date: '2025-07-07',
    time: '21:00',
    stage: '스크림',
    teamA: '뱅',
    teamB: '실프',
    scoreA: 1,
    scoreB: 0,
    status: 'live',
    maps: ['오리건', '해안선', '빌라'],
    isScrim: true,
    sets: [],
  },
  {
    id: 13,
    date: '2025-07-07',
    time: '22:30',
    stage: '스크림',
    teamA: '빅헤드',
    teamB: '뱅',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: true,
    sets: [],
  },
  {
    id: 14,
    date: '2025-07-07',
    time: '22:30',
    stage: '스크림',
    teamA: '핑맨',
    teamB: '실프',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: true,
    sets: [],
  },
  {
    id: 15,
    date: '2025-07-08',
    time: '21:00',
    stage: '스크림',
    teamA: '팀 A',
    teamB: '팀 D',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: true,
    sets: [],
  },
  {
    id: 16,
    date: '2025-07-08',
    time: '21:00',
    stage: '스크림',
    teamA: '팀 B',
    teamB: '팀 C',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: true,
    sets: [],
  },
  {
    id: 17,
    date: '2025-07-08',
    time: '22:30',
    stage: '스크림',
    teamA: '팀 A',
    teamB: '팀 B',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: true,
    sets: [],
  },
  {
    id: 18,
    date: '2025-07-08',
    time: '22:30',
    stage: '스크림',
    teamA: '팀 C',
    teamB: '팀 D',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: true,
    sets: [],
  },
  {
    id: 19,
    date: '2025-07-09',
    time: '21:00',
    stage: '스크림',
    teamA: '팀 A',
    teamB: '팀 C',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: true,
    sets: [],
  },
  {
    id: 20,
    date: '2025-07-09',
    time: '21:00',
    stage: '스크림',
    teamA: '팀 B',
    teamB: '팀 D',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: true,
    sets: [],
  },
  {
    id: 21,
    date: '2025-07-09',
    time: '22:30',
    stage: '스크림',
    teamA: '팀 A',
    teamB: '팀 D',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: true,
    sets: [],
  },
  {
    id: 22,
    date: '2025-07-09',
    time: '22:30',
    stage: '스크림',
    teamA: '팀 B',
    teamB: '팀 C',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: true,
    sets: [],
  },
  {
    id: 23,
    date: '2025-07-10',
    time: '21:00',
    stage: '스크림',
    teamA: '팀 A',
    teamB: '팀 B',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: true,
    sets: [],
  },
  {
    id: 24,
    date: '2025-07-10',
    time: '21:00',
    stage: '스크림',
    teamA: '팀 C',
    teamB: '팀 D',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: true,
    sets: [],
  },
  {
    id: 25,
    date: '2025-07-10',
    time: '22:30',
    stage: '스크림',
    teamA: '팀 A',
    teamB: '팀 C',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: true,
    sets: [],
  },
  {
    id: 26,
    date: '2025-07-10',
    time: '22:30',
    stage: '스크림',
    teamA: '팀 C',
    teamB: '팀 D',
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    maps: ['미정', '미정', '미정'],
    isScrim: true,
    sets: [],
  },
] as const
